#!/bin/bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet, 
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#
wget https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
tar xzf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
mkdir /swift
mv swift-5.1.3-RELEASE-ubuntu18.04 /swift/5.1.3
rm -rf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz 

ln -s /swift/5.1.3/usr/bin/swift /usr/bin/swift

swift --version

git clone https://github.com/vapor/toolbox.git
cd toolbox
swift build
ln -s /root/toolbox/.build/debug/vapor /usr/bin/vapor

vapor --help
